ZSHDIR=$HOME/dotfiles/.zsh

# Enable autocomplete
autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Configure history
setopt extended_history         # record timestamp of command in HISTFILE
setopt hist_expire_dups_first   # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups         # ignore duplicated commands history list
setopt hist_verify              # show command with history expansion to user before running it
setopt append_history           # add commands to HISTFILE on shell exit

# Source plugins
source $ZSHDIR/plugins/fixls.zsh
source $ZSHDIR/plugins/ohmyzsh/plugins/git/git.plugin.zsh
source $ZSHDIR/plugins/ohmyzsh/plugins/virtualenv/virtualenv.plugin.zsh
source $ZSHDIR/plugins/prompt.zsh
source $ZSHDIR/plugins/vim_mode.zsh
source $ZSHDIR/plugins/zsh-z/zsh-z.plugin.zsh
source $ZSHDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Use prefix of what's typed when searching history with arrows
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search

# Set system variables
export VISUAL=vim   # Default to vim editor
export EDITOR=vim
chpwd() ls          # Always ls after cd
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Source aliases
source $ZSHDIR/alias.sh

# Source local (machine-specific) configuration if present
if [ -f $ZSHDIR/local.sh ]; then
    source $ZSHDIR/local.sh
fi
