ZSHDIR=$HOME/dotfiles/zsh

# Enable autocomplete
autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Set POSIX variables
export VISUAL=vim
export EDITOR=vim

# Source plugins
source $ZSHDIR/plugins/fixls.zsh
source $ZSHDIR/plugins/ohmyzsh/plugins/git/git.plugin.zsh
source $ZSHDIR/plugins/ohmyzsh/plugins/virtualenv/virtualenv.plugin.zsh
source $ZSHDIR/plugins/prompt.zsh
source $ZSHDIR/plugins/vim_mode.zsh
source $ZSHDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSHDIR/plugins/zsh-z/zsh-z.plugin.zsh

# Source aliases
source $ZSHDIR/alias.sh

# Source local (machine-specific) configuration if present
if [ -f $ZSHDIR/local.sh ]; then
    source $ZSHDIR/local.sh
fi

# Configure history
export HISTFILE=$ZSHDIR/history
export HISTSIZE=100000
export SAVEHIST=100000
setopt extended_history         # record timestamp of command in HISTFILE
setopt hist_find_no_dups        # do not show duplicate commands when searching through history
setopt hist_ignore_dups         # do not record commands that are the same as the last recorded command
setopt hist_verify              # history expansion shows command instead of executing immediately
setopt inc_append_history_time  # add commands to HISTFILE immediately after execution

# Use prefix of what is typed when searching history with arrows
autoload -Uz up-line-or-beginning-search
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search

# Miscellaneous
chpwd() ls  # Always ls after cd
export VIRTUAL_ENV_DISABLE_PROMPT=1
